[package]
name = "layer8-interceptor-rs"
version = "0.0.14"
edition = "2021"
authors = ["Osoro Bironga <fanosoro@gmail.com>"]
readme = "README.md"

[lib]
crate-type = ["cdylib"]

[dependencies]
secp256k1 = { version = "0.29.1", no-default-features = true, features = [
    "rand-std",
    "hashes-std",
] }
rand = { version = "0.8.5", features = ["small_rng"] }
base64 = { version = "0.22.1", no-default-features = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2.5.2"
wasm-bindgen-futures = "0.4"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
reqwest = "0.12.7"
lazy_static = "1.5.0"
js-sys = "0.3.70"
serde-wasm-bindgen = "0.6.5"
getrandom = { version = "0.2.8", features = [
    "js", # transient dependency of aes-gcm, we need the js feature 
] }
aes-gcm = "0.10.3"

[profile.release]
# We want to optimize for size
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
