[package]
name = "layer8-interceptor-rs"
version = "0.0.14"
edition = "2021"
authors = ["Osoro Bironga <fanosoro@gmail.com>"]
readme = "README.md"
categories = ["wasm"]

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
secp256k1 = { version = "0.29.1", no-default-features = true, features = [
    "rand-std",
    "hashes-std",
] }
rand = { version = "0.8.5", features = ["small_rng"] }
base64 = { version = "0.22.1", no-default-features = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2.5.2"
wasm-bindgen-futures = "0.4"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
reqwest = "0.12.7"
lazy_static = "1.5.0"
js-sys = "0.3.70"
serde-wasm-bindgen = "0.6.5"
getrandom = { version = "0.2.8", features = [
    "js", # transient dependency of aes-gcm, we need the js feature 
] }
aes-gcm = "0.10.3"

[dev-dependencies]
layer8-interceptor-rs = { path = "../layer8-interceptor-rs", no-default-features = true, features = [
    "no-js",
] }
rstest = "0.22.0"

[features]
default = ["js", "no-js"]
# This feature enables the wasmbindgen types and functions
js = ["no-js"]
# This feature exports the crypto and types from the library without the js wasm-bindgen functions, if you're interested in the crypto and types you can enable this feature
no-js = []
