name: Publish to npm

on:
  pull_request: # Testing experimental npm publishes
  # release:
  #   types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          override-file: Cargo.toml
          target: wasm32-unknown-unknown

      - name: Build
        run: |
          cargo install wasm-pack
          wasm-pack build --target bundler --all-features --release
          sudo apt-get install gawk -y
          gawk -f post_build.gawk ./pkg/package.json > ./pkg/package.json.tmp && mv ./pkg/package.json.tmp ./pkg/package.json
          gawk -f post_build.gawk ./pkg/layer8_interceptor_rs.js > ./pkg/layer8_interceptor_rs.js.tmp && mv ./pkg/layer8_interceptor_rs.js.tmp ./pkg/layer8_interceptor_rs.js

      - name: Install npm
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
          registry: https://registry.npmjs.org
          access: public
          package: ./pkg
