name: Publish to npm

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          override-file: Cargo.toml
          target: wasm32-unknown-unknown

      - name: Install wasm-pack and wasm32-unknown-unknown target
        run: | 
            cargo install wasm-pack
    
      - name: Install npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build and publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: |
          wasm-pack build --target web
          cd pkg
          npm publish --access public --token $NPM_TOKEN
